### ISSUE TITLE
Using browser-only version of superagent in non-browser environment

### ISSUE THREAD

**Issue by chrisrodriguezmbww** [MurhafSousli/ngx-bar-rating#42]
Using browser-only version of superagent in non-browser environment
/Users/chris.rodriguez2/Documents/Projects/grceri/node_modules/ngx-bar-rating/component/bar-rating.component.js:1
(function (exports, require, module, __filename, __dirname) { import { Component, Input, Output, ChangeDetectionStrategy, EventEmitter, forwardRef, ChangeDetectorRef } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.ngx-bar-rating/component/bar-rating.component (/Users/chris.rodriguez2/Documents/Projects/grceri/dist/server/main.js:11199:18)

**Comment by kdevsoftware** [comment]
hi, @chrisrodriguezmbww .
did you already fix the issue you mentioned?
if yes, would you please teach me how to fix that issue?

thanks.
